FROM python:3.11.9-bullseye

WORKDIR /data

RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends iproute2 tcpdump iputils-ping

# RUN git clone --depth 1 https://gitee.com/lh0xf/nidsfuzz.git nidsfuzz

COPY ./nidsfuzz /nidsfuzz/nidsfuzz
COPY ./requirements.txt /nidsfuzz/requirements.txt

WORKDIR /nidsfuzz

RUN pip install -r requirements.txt

