FROM ubuntu:22.04

RUN sed -i 's/archive.ubuntu.com/mirrors.hust.edu.cn/g' /etc/apt/sources.list && \
    apt-get update && apt-get dist-upgrade -y

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends build-essential libpcap-dev libpcre3-dev \
    libnet1-dev zlib1g-dev luajit hwloc libdnet-dev libdumbnet-dev bison flex liblzma-dev openssl libssl-dev pkg-config \
    libhwloc-dev cmake cpputest libsqlite3-dev uuid-dev libcmocka-dev libnetfilter-queue-dev libmnl-dev autotools-dev \
    libluajit-5.1-dev libunwind-dev git wget libtool libfl-dev
RUN apt-get install -y flex iproute2 iptables tcpdump

WORKDIR /snort_src

RUN cd /snort_src && \
    wget --no-check-certificate https://github.com/snort3/libdaq/archive/refs/tags/v3.0.17.tar.gz -O libdaq-3.0.17.tar.gz && \
    tar -xzf libdaq-3.0.17.tar.gz
RUN cd /snort_src/libdaq-3.0.17 && ./bootstrap && ./configure && make -j12 && make install

RUN ldconfig

RUN cd /snort_src && \
    wget --no-check-certificate https://github.com/snort3/snort3/archive/refs/tags/3.6.0.0.tar.gz -O snort3-3.6.0.0.tar.gz && \
    tar -xzf snort3-3.6.0.0.tar.gz
RUN cd /snort_src/snort3-3.6.0.0 && ./configure_cmake.sh --prefix=/usr/local --enable-address-sanitizer --enable-thread-sanitizer && \
    cd build && make -j12 && make install

WORKDIR /data

# TEST
# RUN /usr/local/bin/snort -V
# RUN snort -c /usr/local/etc/snort/snort.lua
# stdbuf -oL snort -c /usr/local/etc/snort/snort.lua -i eth0 -R /data/rules/local.rules -A fast -s 65535 -k none --lua 'event_queue = { log = 1000 }; alert_fast = { packet = true }' > /data/log/snort3.log









