FROM ubuntu:22.04

RUN sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y autoconf automake build-essential ccache clang curl git \
    gosu jq libbpf-dev libcap-ng0 libcap-ng-dev libelf-dev \
    libevent-dev libgeoip-dev libhiredis-dev libjansson-dev \
    liblua5.1-dev libmagic-dev libnet1-dev libpcap-dev \
    libpcre2-dev libtool libyaml-0-2 libyaml-dev m4 make \
    pkg-config python3 python3-dev python3-yaml zlib1g \
    zlib1g-dev iproute2 tcpdump iptables

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    echo 'export PATH="${PATH}:/root/.cargo/bin"' >> ~/.bashrc && \
    export PATH="${PATH}:/root/.cargo/bin" && \
    cargo install --force cbindgen

WORKDIR /data

RUN git clone https://github.com/OISF/suricata.git suricata && \
    cd /data/suricata && \
    git clone https://github.com/OISF/libhtp

RUN export PATH="${PATH}:/root/.cargo/bin" && \
    cd /data/suricata && \
    ./autogen.sh && \
    ./configure --prefix=/usr/ --sysconfdir=/etc/ --localstatedir=/var/ --enable-nfqueue && \
    make -j4 && make install && make install-conf

RUN update-alternatives --set iptables /usr/sbin/iptables-legacy && \
    update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

# echo 1 > /proc/sys/net/ipv4/ip_forward

# TEST
# suricata --build-info
# suricata -c /etc/suricata/suricata.yaml -S /data/rules/local.rules -i eth1 -l /data/log