version: '3'
services:
    initiator:
        image: nids/nidsfuzz
        container_name: initiator
        volumes:
            - replay:/data/replay/:ro,nocopy
            - initiator-log:/data/log
            - snort3-log:/data/snort3
            - suricata-log:/data/suricata
        command: /bin/bash -c "
            cd /nidsfuzz/nidsfuzz && 
            ip route add 192.168.0.0/16 via 172.18.0.11 dev eth0 && 
            sleep 4 && 
            LOG_DIR=/data/log python ./main.py --replay
            --traffic /data/replay/traffic.bin
            --initiator 172.18.0.10
            --responder 192.168.0.10
            --echo_port ${ECHO_PORT}
            --data_port ${DATA_PORT}
            "
        networks:
            left:
                ipv4_address: 172.18.0.10
        depends_on:
            - mirror
            - responder
            - suricata
            - snort3
        privileged: true

volumes:
    replay:
        external: true